In [48]:
import numpy as np
n=3
arr=[]
for i in range(n):
    row = list(map(int,input().split()))
    arr.append(row)
print(arr)   
arr1=np.array(arr) 



2 3 4 1
2 4 5 6
8 6 5 4
[[2, 3, 4, 1], [2, 4, 5, 6], [8, 6, 5, 4]]


In [37]:
print(arr1[0,:])
print(arr1[:,0])
print(arr1[:,2])
print(arr[0][:])
arr1

[2 3 3 4]
[2 0 1]
[3 2 2]
[3, 4, 2, 3]


array([[2, 3, 3, 4],
       [0, 4, 2, 1],
       [1, 2, 2, 1]])

### How to sort array 

In [43]:
## sort columns
arr1[:,2]=sorted(arr1[:,2])
print(arr1)

## sort rows
arr1[0,:] = sorted(arr1[0,:])
print(arr1)

## wrong way to sort array
arr1 = sorted(arr1[0,:])
print(arr1)

[[3 4 1 3]
 [8 5 2 2]
 [3 2 3 2]]
[[1 3 3 4]
 [8 5 2 2]
 [3 2 3 2]]
[1, 3, 3, 4]


In [66]:
a=np.array([[1,2,3],[2,3,5]])
b=np.array([[6,2,7],[25,6,5]])

In [70]:
## add two numpy array
z = a+b
# a*b
# a//b
print(z)

[[ 6  4 21]
 [50 18 25]]


In [72]:
# b*2
z=b[0,:]*2
print(z)

[12  4 14]


## Calculate the rotation distance for a sorted rotated array
#### For example: 
input:
4, 5, 6, 1, 2, 3
output:
3

In [3]:
arr = list(map(int,input().split()))
print(arr.index(min(arr)))

4 5 6 1 2 3
3


In [3]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,1,2])
a+b

array([4, 6, 4, 6])

[1, 2, 3, 4, 3, 4, 1, 2]