In [ ]:
import numpy as np
n=3
arr=[]
for i in range(n):
    row = list(map(int,input().split()))
    arr.append(row)
print(arr)   
arr1=np.array(arr) 
 


4 2 3 5
3 4 1 2


Remove square brackets from list 
using str() + list slicing

In [1]:
test_list = [5, 6, 8, 9, 10, 21] 

print("The original list is : " + str(test_list)) 

# Remove square brackets from list 
# using str() + list slicing 
res = str(test_list)[1:-1] 

# printing result 
print("List after removing square brackets : " + "".join(res.split(",")) )

The original list is : [5, 6, 8, 9, 10, 21]
List after removing square brackets : 5 6 8 9 10 21


In [11]:
def duplicate(l):
    result= []
    for i in l:
        if not i in result:
            result.append(i)
    return result        

In [12]:
print duplicate([1,2,2,1,3,4,3])

[1, 2, 3, 4]


In [27]:
l = [1,2,2,3,1,2,3]
print list(set(l))


[1, 2, 3]


In [1]:

def count_c(l1):
    result={}
    for i in l1:
        if i not in result:
            result[i]=1
        else:
            result[i]+=1
    for key , value in enumerate(result):
        print key,value
          
print count_c('aaabbcd')        

0 a
1 c
2 b
3 d
None


In [1]:
def subset(l1,l2):
    temp = dict([(e,1) for e in l2])
    for i in l1:
        if not i in temp:
            return False
    return True
subset([1,2,3],[1,2,3,4])



True

# Gcd Number

In [5]:
def gcd(a,b):
    if(b==0):
        return a
    else:
        return gcd(b,a % b)
print(gcd(6,12))    

6


In [7]:
from fractions import gcd
print gcd(6,12)

6


In [15]:
names = ['peter','john','alex','julia']
rollno = [101,102,103,104]
x = [6,7,9]
dictionary = dict(zip(names,rollno))
print(dictionary)
a,b,c = x
print a,b,c


{'john': 102, 'peter': 101, 'alex': 103, 'julia': 104}
6 7 9


In [12]:
dictionary.items()

[('john', 102), ('peter', 101), ('alex', 103), ('julia', 104)]

In [9]:
def fun1():
    base  = raw_input()
    num = int(base[0])
    al = base[1]
    print fun2(num,al)
    
    
def fun2(num,al):
    
    return (int(num) * pow(17,1) + ord(al) * pow(17,0)) 
fun1()

1A
82


In [8]:
print(chr(65),ord('A'))

('A', 65)


# simple interest tcs

In [15]:
n = int(input())
for i in range(10):
    amt = n + ((n/100) * 5)
    n = amt
    print("%.2f" %amt)

1000
1050.000
1100.000
1155.000
1210.000
1270.000
1330.000
1395.000
1460.000
1530.000
1605.000


# Rotate Left

In [4]:
a = 'rhdt'
d = 2
def rotateLeft(a,d):
    
    return a[d:] + a[:d]
print(rotateLeft(a,d))

dtrh


In [4]:
a[2:] + a[:2]

[3, 4, 1, 2]

# Rotate Right

In [6]:
def rotateRight(a,d):
    
    return a[-d:] + a[:d]

a="rhdt"
print(rotateRight(a,d))
# [2,3,5,2,3]-->[3,2,,3,5,2]-->[2,3,,2,3,5]


dtrh


# Minimum number of swap

In [6]:
def minimumSwaps(arr):
    n = len(arr)
    count = 0
    for i in range(n):
        min = i
        for j in range(i+1,n):
            if(arr[j]<arr[min]):
                min = j
        if(min!= i):
            temp = arr[j]
            arr[j] = arr[i]
            arr[i] = temp
            count+=1
    return count
minimumSwaps([2,4,31,1])

3

# cutting rod

In [1]:
import sys 
  
# A utility function to get the 
# maximum of two integers 
def max(a, b): 
    return a if (a > b) else b 
      
# Returns the best obtainable price for a rod of length n  
# and price[] as prices of different pieces 
def cutRod(price, n): 
    if(n <= 0): 
        return 0
    max_val = -sys.maxsize-1
      
    # Recursively cut the rod in different pieces   
    # and compare different configurations 
    for i in range(0, n): 
        max_val = max(max_val, price[i] + 
                      cutRod(price, n - i - 1)) 
    return max_val 
  
# Driver code 
arr = [1, 5, 8, 9, 10, 17, 17, 20] 
size = len(arr) 
print("Maximum Obtainable Value is", cutRod(arr, size))

('Maximum Obtainable Value is', 22)


# Reverse until number becames palindrome

In [ ]:
Num =int(input())
palindrome(Num)  
def palindrome(Num):
    while(True):
        Num = Num + rev(Num)
        if(pal1(Num)):
            print "palindrome"
            break

def rev(n):
    n = str(n)
    return int(n[::-1])
def pal1(Num):
    Num = str(Num)
    if Num == Num[::-1]:
        return True
    else:
        return False
    

   

In [24]:
def fibo(n):
    f0,f1,f2 = 0,1,0
    print f0
    print f1
    for i in range(n):
        f2 = f0 + f1
        f0 = f1
        f1 = f2
        print f2
fibo(1)  

0
1
1


In [26]:
n = "this is string"
print n.count(" ") 

2


# Rearrange array

In [1]:
def rearrange(arr):
    n = len(arr)
    new = []
    for i in range(0,n):
        for j in range(n-1,i+1):
            if arr[i] != arr[j] :
                new.append([j,i])
            else:
                 new.append(j)
    return new     
    
print rearrange([1,2,3,4,5])    

[4]


itertools unique combinations

In [3]:
from itertools import combinations 

def rSubset(arr, r): 
    return list(combinations(arr, r)) 


arr = [1, 2, 3, 4] 
r = 2
print rSubset(arr, r)
 
   

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]


# pattern

In [9]:
n = int(input())
for i in range(1,n + 1):
    if i is 1:
        print i
    else:
        print(str(i) + ("*" + str(i)) * (i-1))

for i in range(n,0,-1):
    if i is 1:
        print i
    else:
        print(str(i) + ("*" + str(i)) * (i-1))    
        

4
1
2*2
3*3*3
4*4*4*4
4*4*4*4
3*3*3
2*2
1


# Numpy array


In [11]:
import numpy as np
arr = np.array([[1,2,3],[3,2,3],[4,5,6]])
   
print arr[0,1]

2


In [12]:
arr[0,-1]
arr[0:3]
arr[0][0:3]

array([1, 2, 3])

In [42]:
for i in range(3):
    print(arr[i][:3])

[1 2 3]
[3 2 3]
[4 5 6]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [16]:
arr = [1,2,3,4,3]
arr.remove(arr[1])
print(sorted(arr))

[1, 3, 3, 4]


In [3]:
for i in range(2):
    yr,amt=[int(x) for x in raw_input().split(" ")]
    

4 5
2 3


# dictionary operations IMP

using dict.items() function

In [7]:
l=['a','b','c','d']

dic=dict([(x,1) for x in l])
print(dic)
for key,value in dic.items():
    print(key,value)


{'a': 1, 'c': 1, 'b': 1, 'd': 1}
('a', 1)
('c', 1)
('b', 1)
('d', 1)


using enumarate function

In [8]:
from collections import Counter
l=['a','b','c','d']

dic=dict([(x,1) for x in l])
# dic = Counter(l)
for value,key in enumerate(dic):
    print(key,value)

# pop element from dictionary
#parameter should be key
dic.pop('b')
dic['e'] = 5

{'a': 1, 'c': 1, 'b': 1, 'd': 1}
('a', 0)
('c', 1)
('b', 2)
('d', 3)


In [9]:
names = ['peter','john','alex','julia']
rollno = [101,102,103,104]
x = [6,7,9]
dictionary = dict(zip(names,rollno))
print(dictionary)
a,b,c = x
print a,b,c


(0, 'a')
(1, 'b')
(2, 'c')
(3, 'd')


1

{'c': 1, 'd': 1}
